
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef CANOPENSHELLSLAVEOD_H
#define CANOPENSHELLSLAVEOD_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 CANOpenShellSlaveOD_valueRangeTest (UNS8 typeValue, void * value);
const indextable * CANOpenShellSlaveOD_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data CANOpenShellSlaveOD_Data;

#endif // CANOPENSHELLSLAVEOD_H
