
/* File generated by gen_cfile.py. Should not be modified. */

#include "TestMaster.h"

/**************************************************************************/
/* Declaration of the mapped variables                                    */
/**************************************************************************/
UNS8 DO = 0x0;		/* Mapped at index 0x2000, subindex 0x00 */
INTEGER16 AO1 = 0x0;		/* Mapped at index 0x2001, subindex 0x00 */
INTEGER16 AO2 = 0x0;		/* Mapped at index 0x2002, subindex 0x00 */
INTEGER16 AO3 = 0x0;		/* Mapped at index 0x2003, subindex 0x00 */
INTEGER16 AO4 = 0x0;		/* Mapped at index 0x2004, subindex 0x00 */
INTEGER16 AI1 = 0x0;		/* Mapped at index 0x2005, subindex 0x00 */
INTEGER16 AI2 = 0x0;		/* Mapped at index 0x2006, subindex 0x00 */
INTEGER16 AI3 = 0x0;		/* Mapped at index 0x2007, subindex 0x00 */
INTEGER16 AI4 = 0x0;		/* Mapped at index 0x2008, subindex 0x00 */
INTEGER16 AI5 = 0x0;		/* Mapped at index 0x2009, subindex 0x00 */
INTEGER16 AI6 = 0x0;		/* Mapped at index 0x200A, subindex 0x00 */
INTEGER16 AI7 = 0x0;		/* Mapped at index 0x200B, subindex 0x00 */
INTEGER16 AI8 = 0x0;		/* Mapped at index 0x200C, subindex 0x00 */
UNS8 DI1 = 0x0;		/* Mapped at index 0x200F, subindex 0x00 */
UNS8 DI2 = 0x0;		/* Mapped at index 0x2010, subindex 0x00 */
UNS8 DI3 = 0x0;		/* Mapped at index 0x2011, subindex 0x00 */
UNS8 DI4 = 0x0;		/* Mapped at index 0x2012, subindex 0x00 */
UNS8 DI5 = 0x0;		/* Mapped at index 0x2013, subindex 0x00 */
UNS8 DI6 = 0x0;		/* Mapped at index 0x2014, subindex 0x00 */
UNS8 DI7 = 0x0;		/* Mapped at index 0x2015, subindex 0x00 */
UNS8 DI8 = 0x0;		/* Mapped at index 0x2016, subindex 0x00 */

/**************************************************************************/
/* Declaration of the value range types                                   */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 TestMaster_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 TestMaster_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 TestMaster_iam_a_slave = 0;

TIMER_HANDLE TestMaster_heartBeatTimers[1] = {TIMER_NONE};

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 TestMaster_obj1000 = 0x191;	/* 401 */
                    subindex TestMaster_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 TestMaster_obj1001 = 0x0;	/* 0 */
                    subindex TestMaster_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 TestMaster_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t TestMaster_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex TestMaster_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 TestMaster_obj1005 = 0x40000080;	/* 1073741952 */
                    ODCallback_t TestMaster_Index1005_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestMaster_Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1005 }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 TestMaster_obj1006 = 0xC350;	/* 50000 */
                    ODCallback_t TestMaster_Index1006_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestMaster_Index1006[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1006 }
                     };

/* index 0x1014 :   Emergency COB ID */
                    UNS32 TestMaster_obj1014 = 0x0;   /* 0 */

/* index 0x1016 :   Consumer Heartbeat Time. */
                    UNS8 TestMaster_highestSubIndex_obj1016 = 1; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1016[] = 
                    {
                      0x4005DC	/* 4195804 */
                    };
                    subindex TestMaster_Index1016[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1016 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1016[0] }
                     };

/* index 0x1017 :   Producer Heartbeat Time */ 
                    UNS16 TestMaster_obj1017 = 0x0;   /* 0 */

/* index 0x1018 :   Identity. */
                    UNS8 TestMaster_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex TestMaster_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1018_Serial_Number }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x640;	/* 1600 */
                    UNS32 TestMaster_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x5C0;	/* 1472 */
                    UNS8 TestMaster_obj1280_Node_ID_of_the_SDO_Server = 0x40;	/* 64 */
                    subindex TestMaster_Index1280[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1280 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1280_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1280_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1280_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1400 = 5; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1400_COB_ID_used_by_PDO = 0x1C0;	/* 448 */
                    UNS8 TestMaster_obj1400_Transmission_Type = 0x1;	/* 1 */
                    UNS16 TestMaster_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1400_Event_Timer = 0x0;	/* 0 */
                    subindex TestMaster_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1400_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1400_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1400_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1400_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1400_Event_Timer }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1401 = 5; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1401_COB_ID_used_by_PDO = 0x2C0;	/* 704 */
                    UNS8 TestMaster_obj1401_Transmission_Type = 0x1;	/* 1 */
                    UNS16 TestMaster_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1401_Event_Timer = 0x0;	/* 0 */
                    subindex TestMaster_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1401 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1401_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1401_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1401_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1401_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1401_Event_Timer }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1402 = 5; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1402_COB_ID_used_by_PDO = 0x3C0;	/* 960 */
                    UNS8 TestMaster_obj1402_Transmission_Type = 0x1;	/* 1 */
                    UNS16 TestMaster_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1402_Event_Timer = 0x0;	/* 0 */
                    subindex TestMaster_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1402 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1402_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1402_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1402_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1402_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1402_Event_Timer }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1600 = 8; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1600[] = 
                    {
                      0x200F0001,	/* 537853953 */
                      0x20100001,	/* 537919489 */
                      0x20110001,	/* 537985025 */
                      0x20120001,	/* 538050561 */
                      0x20130001,	/* 538116097 */
                      0x20140001,	/* 538181633 */
                      0x20150001,	/* 538247169 */
                      0x20160001	/* 538312705 */
                    };
                    subindex TestMaster_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1600[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1600[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1600[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1600[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1600[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1600[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1600[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1600[7] }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1601 = 4; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1601[] = 
                    {
                      0x20050010,	/* 537198608 */
                      0x20060010,	/* 537264144 */
                      0x20070010,	/* 537329680 */
                      0x20080010	/* 537395216 */
                    };
                    subindex TestMaster_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1601 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1601[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1601[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1601[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1601[3] }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1602 = 4; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1602[] = 
                    {
                      0x20090010,	/* 537460752 */
                      0x200A0010,	/* 537526288 */
                      0x200B0010,	/* 537591824 */
                      0x200C0010	/* 537657360 */
                    };
                    subindex TestMaster_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1602 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1602[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1602[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1602[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1602[3] }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1800 = 5; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1800_COB_ID_used_by_PDO = 0x240;	/* 576 */
                    UNS8 TestMaster_obj1800_Transmission_Type = 0x1;	/* 1 */
                    UNS16 TestMaster_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1800_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t TestMaster_Index1800_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex TestMaster_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1800 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1800_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1800_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1800_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1800_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1800_Event_Timer }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1801 = 5; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1801_COB_ID_used_by_PDO = 0x340;	/* 832 */
                    UNS8 TestMaster_obj1801_Transmission_Type = 0x1;	/* 1 */
                    UNS16 TestMaster_obj1801_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1801_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t TestMaster_Index1801_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex TestMaster_Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1801 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1801_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1801_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1801_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1801_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1801_Event_Timer }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1A00 = 1; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1A00[] = 
                    {
                      0x20000008	/* 536870920 */
                    };
                    subindex TestMaster_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1A00 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A00[0] }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1A01 = 4; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1A01[] = 
                    {
                      0x20010010,	/* 536936464 */
                      0x20020010,	/* 537002000 */
                      0x20030010,	/* 537067536 */
                      0x20040010	/* 537133072 */
                    };
                    subindex TestMaster_Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1A01 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A01[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A01[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A01[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A01[3] }
                     };

/* index 0x2000 :   Mapped variable DO */
                    subindex TestMaster_Index2000[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&DO }
                     };

/* index 0x2001 :   Mapped variable AO1 */
                    subindex TestMaster_Index2001[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&AO1 }
                     };

/* index 0x2002 :   Mapped variable AO2 */
                    subindex TestMaster_Index2002[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&AO2 }
                     };

/* index 0x2003 :   Mapped variable AO3 */
                    subindex TestMaster_Index2003[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&AO3 }
                     };

/* index 0x2004 :   Mapped variable AO4 */
                    subindex TestMaster_Index2004[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&AO4 }
                     };

/* index 0x2005 :   Mapped variable AI1 */
                    subindex TestMaster_Index2005[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&AI1 }
                     };

/* index 0x2006 :   Mapped variable AI2 */
                    subindex TestMaster_Index2006[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&AI2 }
                     };

/* index 0x2007 :   Mapped variable AI3 */
                    subindex TestMaster_Index2007[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&AI3 }
                     };

/* index 0x2008 :   Mapped variable AI4 */
                    subindex TestMaster_Index2008[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&AI4 }
                     };

/* index 0x2009 :   Mapped variable AI5 */
                    subindex TestMaster_Index2009[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&AI5 }
                     };

/* index 0x200A :   Mapped variable AI6 */
                    subindex TestMaster_Index200A[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&AI6 }
                     };

/* index 0x200B :   Mapped variable AI7 */
                    subindex TestMaster_Index200B[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&AI7 }
                     };

/* index 0x200C :   Mapped variable AI8 */
                    subindex TestMaster_Index200C[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&AI8 }
                     };

/* index 0x200F :   Mapped variable DI1 */
                    subindex TestMaster_Index200F[] = 
                     {
                       { RW, boolean, sizeof (UNS8), (void*)&DI1 }
                     };

/* index 0x2010 :   Mapped variable DI2 */
                    subindex TestMaster_Index2010[] = 
                     {
                       { RW, boolean, sizeof (UNS8), (void*)&DI2 }
                     };

/* index 0x2011 :   Mapped variable DI3 */
                    subindex TestMaster_Index2011[] = 
                     {
                       { RW, boolean, sizeof (UNS8), (void*)&DI3 }
                     };

/* index 0x2012 :   Mapped variable DI4 */
                    subindex TestMaster_Index2012[] = 
                     {
                       { RW, boolean, sizeof (UNS8), (void*)&DI4 }
                     };

/* index 0x2013 :   Mapped variable DI5 */
                    subindex TestMaster_Index2013[] = 
                     {
                       { RW, boolean, sizeof (UNS8), (void*)&DI5 }
                     };

/* index 0x2014 :   Mapped variable DI6 */
                    subindex TestMaster_Index2014[] = 
                     {
                       { RW, boolean, sizeof (UNS8), (void*)&DI6 }
                     };

/* index 0x2015 :   Mapped variable DI7 */
                    subindex TestMaster_Index2015[] = 
                     {
                       { RW, boolean, sizeof (UNS8), (void*)&DI7 }
                     };

/* index 0x2016 :   Mapped variable DI8 */
                    subindex TestMaster_Index2016[] = 
                     {
                       { RW, boolean, sizeof (UNS8), (void*)&DI8 }
                     };

const indextable TestMaster_objdict[] = 
{
  { (subindex*)TestMaster_Index1000,sizeof(TestMaster_Index1000)/sizeof(TestMaster_Index1000[0]), 0x1000},
  { (subindex*)TestMaster_Index1001,sizeof(TestMaster_Index1001)/sizeof(TestMaster_Index1001[0]), 0x1001},
  { (subindex*)TestMaster_Index1005,sizeof(TestMaster_Index1005)/sizeof(TestMaster_Index1005[0]), 0x1005},
  { (subindex*)TestMaster_Index1006,sizeof(TestMaster_Index1006)/sizeof(TestMaster_Index1006[0]), 0x1006},
  { (subindex*)TestMaster_Index1016,sizeof(TestMaster_Index1016)/sizeof(TestMaster_Index1016[0]), 0x1016},
  { (subindex*)TestMaster_Index1018,sizeof(TestMaster_Index1018)/sizeof(TestMaster_Index1018[0]), 0x1018},
  { (subindex*)TestMaster_Index1280,sizeof(TestMaster_Index1280)/sizeof(TestMaster_Index1280[0]), 0x1280},
  { (subindex*)TestMaster_Index1400,sizeof(TestMaster_Index1400)/sizeof(TestMaster_Index1400[0]), 0x1400},
  { (subindex*)TestMaster_Index1401,sizeof(TestMaster_Index1401)/sizeof(TestMaster_Index1401[0]), 0x1401},
  { (subindex*)TestMaster_Index1402,sizeof(TestMaster_Index1402)/sizeof(TestMaster_Index1402[0]), 0x1402},
  { (subindex*)TestMaster_Index1600,sizeof(TestMaster_Index1600)/sizeof(TestMaster_Index1600[0]), 0x1600},
  { (subindex*)TestMaster_Index1601,sizeof(TestMaster_Index1601)/sizeof(TestMaster_Index1601[0]), 0x1601},
  { (subindex*)TestMaster_Index1602,sizeof(TestMaster_Index1602)/sizeof(TestMaster_Index1602[0]), 0x1602},
  { (subindex*)TestMaster_Index1800,sizeof(TestMaster_Index1800)/sizeof(TestMaster_Index1800[0]), 0x1800},
  { (subindex*)TestMaster_Index1801,sizeof(TestMaster_Index1801)/sizeof(TestMaster_Index1801[0]), 0x1801},
  { (subindex*)TestMaster_Index1A00,sizeof(TestMaster_Index1A00)/sizeof(TestMaster_Index1A00[0]), 0x1A00},
  { (subindex*)TestMaster_Index1A01,sizeof(TestMaster_Index1A01)/sizeof(TestMaster_Index1A01[0]), 0x1A01},
  { (subindex*)TestMaster_Index2000,sizeof(TestMaster_Index2000)/sizeof(TestMaster_Index2000[0]), 0x2000},
  { (subindex*)TestMaster_Index2001,sizeof(TestMaster_Index2001)/sizeof(TestMaster_Index2001[0]), 0x2001},
  { (subindex*)TestMaster_Index2002,sizeof(TestMaster_Index2002)/sizeof(TestMaster_Index2002[0]), 0x2002},
  { (subindex*)TestMaster_Index2003,sizeof(TestMaster_Index2003)/sizeof(TestMaster_Index2003[0]), 0x2003},
  { (subindex*)TestMaster_Index2004,sizeof(TestMaster_Index2004)/sizeof(TestMaster_Index2004[0]), 0x2004},
  { (subindex*)TestMaster_Index2005,sizeof(TestMaster_Index2005)/sizeof(TestMaster_Index2005[0]), 0x2005},
  { (subindex*)TestMaster_Index2006,sizeof(TestMaster_Index2006)/sizeof(TestMaster_Index2006[0]), 0x2006},
  { (subindex*)TestMaster_Index2007,sizeof(TestMaster_Index2007)/sizeof(TestMaster_Index2007[0]), 0x2007},
  { (subindex*)TestMaster_Index2008,sizeof(TestMaster_Index2008)/sizeof(TestMaster_Index2008[0]), 0x2008},
  { (subindex*)TestMaster_Index2009,sizeof(TestMaster_Index2009)/sizeof(TestMaster_Index2009[0]), 0x2009},
  { (subindex*)TestMaster_Index200A,sizeof(TestMaster_Index200A)/sizeof(TestMaster_Index200A[0]), 0x200A},
  { (subindex*)TestMaster_Index200B,sizeof(TestMaster_Index200B)/sizeof(TestMaster_Index200B[0]), 0x200B},
  { (subindex*)TestMaster_Index200C,sizeof(TestMaster_Index200C)/sizeof(TestMaster_Index200C[0]), 0x200C},
  { (subindex*)TestMaster_Index200F,sizeof(TestMaster_Index200F)/sizeof(TestMaster_Index200F[0]), 0x200F},
  { (subindex*)TestMaster_Index2010,sizeof(TestMaster_Index2010)/sizeof(TestMaster_Index2010[0]), 0x2010},
  { (subindex*)TestMaster_Index2011,sizeof(TestMaster_Index2011)/sizeof(TestMaster_Index2011[0]), 0x2011},
  { (subindex*)TestMaster_Index2012,sizeof(TestMaster_Index2012)/sizeof(TestMaster_Index2012[0]), 0x2012},
  { (subindex*)TestMaster_Index2013,sizeof(TestMaster_Index2013)/sizeof(TestMaster_Index2013[0]), 0x2013},
  { (subindex*)TestMaster_Index2014,sizeof(TestMaster_Index2014)/sizeof(TestMaster_Index2014[0]), 0x2014},
  { (subindex*)TestMaster_Index2015,sizeof(TestMaster_Index2015)/sizeof(TestMaster_Index2015[0]), 0x2015},
  { (subindex*)TestMaster_Index2016,sizeof(TestMaster_Index2016)/sizeof(TestMaster_Index2016[0]), 0x2016},
};

const indextable * TestMaster_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1005: i = 2;*callbacks = TestMaster_Index1005_callbacks; break;
		case 0x1006: i = 3;*callbacks = TestMaster_Index1006_callbacks; break;
		case 0x1016: i = 4;break;
		case 0x1018: i = 5;break;
		case 0x1280: i = 6;break;
		case 0x1400: i = 7;break;
		case 0x1401: i = 8;break;
		case 0x1402: i = 9;break;
		case 0x1600: i = 10;break;
		case 0x1601: i = 11;break;
		case 0x1602: i = 12;break;
		case 0x1800: i = 13;*callbacks = TestMaster_Index1800_callbacks; break;
		case 0x1801: i = 14;*callbacks = TestMaster_Index1801_callbacks; break;
		case 0x1A00: i = 15;break;
		case 0x1A01: i = 16;break;
		case 0x2000: i = 17;break;
		case 0x2001: i = 18;break;
		case 0x2002: i = 19;break;
		case 0x2003: i = 20;break;
		case 0x2004: i = 21;break;
		case 0x2005: i = 22;break;
		case 0x2006: i = 23;break;
		case 0x2007: i = 24;break;
		case 0x2008: i = 25;break;
		case 0x2009: i = 26;break;
		case 0x200A: i = 27;break;
		case 0x200B: i = 28;break;
		case 0x200C: i = 29;break;
		case 0x200F: i = 30;break;
		case 0x2010: i = 31;break;
		case 0x2011: i = 32;break;
		case 0x2012: i = 33;break;
		case 0x2013: i = 34;break;
		case 0x2014: i = 35;break;
		case 0x2015: i = 36;break;
		case 0x2016: i = 37;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &TestMaster_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status TestMaster_PDO_status[2] = {s_PDO_status_Initializer,s_PDO_status_Initializer};

quick_index TestMaster_firstIndex = {
  0, /* SDO_SVR */
  6, /* SDO_CLT */
  7, /* PDO_RCV */
  10, /* PDO_RCV_MAP */
  13, /* PDO_TRS */
  15 /* PDO_TRS_MAP */
};

quick_index TestMaster_lastIndex = {
  0, /* SDO_SVR */
  6, /* SDO_CLT */
  9, /* PDO_RCV */
  12, /* PDO_RCV_MAP */
  14, /* PDO_TRS */
  16 /* PDO_TRS_MAP */
};

UNS16 TestMaster_ObjdictSize = sizeof(TestMaster_objdict)/sizeof(TestMaster_objdict[0]); 

CO_Data TestMaster_Data = CANOPEN_NODE_DATA_INITIALIZER(TestMaster);

